# Generated by Django 5.0.2 on 2024-02-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostic_Center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='patientlookingtimeto',
            field=models.DateTimeField(null=True),
        ),
    ]
