# Generated by Django 5.0.2 on 2024-02-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostic_Center', '0003_nurse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='degrees',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='jobposition',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='patientlookingtimetfrom',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='patientlookingtimeto',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='spe',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='workingplace',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
