# Generated by Django 5.0.2 on 2024-02-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostic_Center', '0004_remove_doctor_degrees_remove_doctor_jobposition_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
