# Generated by Django 5.0.2 on 2024-02-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
